In [ ]:
!pip install tensorflow_hub

In [ ]:
!pip install tensorflow_text

     |████████████████████████████████| 4.3 MB 7.4 MB/s 


In [ ]:

import tensorflow_hub as hub
import tensorflow_text as text

In [ ]:
preprocess_url = "https://tfhub.dev/tensorflow/bert_en_uncased_preprocess/3" #preprocessing URL goes along with bert
encoder_url = "https://tfhub.dev/tensorflow/bert_en_uncased_L-12_H-768_A-12/4"# THIS IS BERT BASE


In [ ]:
bert_preprocess_model = hub.KerasLayer(preprocess_url)#acts like a sort of pointer and hub is used and preprocess URL is passed

In [ ]:
text_test = ['nice movie indeed','I love python programming']
text_preprocessed = bert_preprocess_model(text_test)
text_preprocessed.keys()#this is a dictionary

dict_keys(['input_type_ids', 'input_mask', 'input_word_ids'])

In [ ]:
text_preprocessed['input_mask']#2 since 2 sentences 2masks for 2 sentences
# input mask 5 ones but sentence has three because  CLS nice movie indeed SEP (TWO TOKENS)
#128 since max length is 128 of a sentence.

<tf.Tensor: shape=(2, 128), dtype=int32, numpy=
array([[1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],
      dtype=int32)>

In [ ]:
text_preprocessed['input_type_ids']#useful if you have multiple words in one statement not really useful here.

<tf.Tensor: shape=(2, 128), dtype=int32, numpy=
array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],
      dtype=int32)>

In [ ]:
text_preprocessed['input_word_ids']#CLS 101 and SEP 102 , 3835,3185,5262 are the unique ids for the words

<tf.Tensor: shape=(2, 128), dtype=int32, numpy=
array([[  101,  3835,  3185,  5262,   102,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0, 

In [ ]:
bert_model = hub.KerasLayer(encoder_url)# we need another layer
bert_results = bert_model(text_preprocessed)# word embedding will be made
# this bert_results is a dictionary

In [ ]:
bert_results.keys()

dict_keys(['encoder_outputs', 'sequence_output', 'default', 'pooled_output'])

In [ ]:
bert_results['pooled_output']# embedding for entire sentence #embedding vector size 768
#this could be used in any task movie review classification , NER etc..

<tf.Tensor: shape=(2, 768), dtype=float32, numpy=
array([[-0.7917739 , -0.21411908,  0.49769524, ...,  0.24465217,
        -0.47334465,  0.8175868 ],
       [-0.9171231 , -0.47935188, -0.78657013, ..., -0.61751795,
        -0.7102685 ,  0.92184293]], dtype=float32)>

In [ ]:
bert_results['sequence_output']# is individual word embedding vectors ,2 sentences
# each individual sentence has padding of 128.
# each word has like "nice" as 786 word embedding vector and etc... #contexualized embedding

<tf.Tensor: shape=(2, 128, 768), dtype=float32, numpy=
array([[[ 0.07292046,  0.0856781 ,  0.14476833, ..., -0.0967708 ,
          0.08722136,  0.07711092],
        [ 0.17839377, -0.19006059,  0.5034938 , ..., -0.05869821,
          0.32717127, -0.15578596],
        [ 0.18701449, -0.43388757, -0.48875144, ..., -0.15502799,
          0.0014513 , -0.24470904],
        ...,
        [ 0.12083092,  0.1288425 ,  0.4645352 , ...,  0.07375517,
          0.17441958,  0.16522051],
        [ 0.07967858, -0.01190688,  0.5022545 , ...,  0.13777749,
          0.21002206,  0.00624583],
        [-0.07212721, -0.28303438,  0.5903336 , ...,  0.47551948,
          0.16668488, -0.0892031 ]],

       [[-0.07900605,  0.36335143, -0.2110159 , ..., -0.17183739,
          0.16299734,  0.67242634],
        [ 0.27883568,  0.4371632 , -0.35764813, ..., -0.04463668,
          0.38315186,  0.58879846],
        [ 1.2037671 ,  1.0727025 ,  0.4840873 , ...,  0.24921009,
          0.40730885,  0.40481815],
        ...,

In [ ]:
len(bert_results['encoder_outputs']) #BERT base len of encoder output is 12 due to BERT Base we using BERT base thats why
#encoder outputs are the outputs of each of the individual encoders

12

In [ ]:
bert_results['encoder_outputs'][0]#looking at the first one

<tf.Tensor: shape=(2, 128, 768), dtype=float32, numpy=
array([[[ 0.12901428,  0.00644744, -0.03614967, ...,  0.04999626,
          0.061492  , -0.02657534],
        [ 1.1753384 ,  1.2140783 ,  1.1569978 , ...,  0.11634351,
         -0.35855356, -0.4049017 ],
        [ 0.03859075,  0.53869987, -0.21089795, ...,  0.21858183,
          0.7260165 , -1.1158606 ],
        ...,
        [-0.07587034, -0.25421894,  0.7075511 , ...,  0.50541973,
         -0.18878677,  0.15028349],
        [-0.1606662 , -0.28089663,  0.5759707 , ...,  0.52758545,
         -0.11141373,  0.02887543],
        [-0.04428162, -0.20279568,  0.5909355 , ...,  0.8133836 ,
         -0.39075807, -0.0260174 ]],

       [[ 0.18903586,  0.02752541, -0.0651374 , ..., -0.00620215,
          0.15053889,  0.03165434],
        [ 0.5916147 ,  0.7589137 , -0.0724066 , ...,  0.61903965,
          0.82928866,  0.16161965],
        [ 1.4460826 ,  0.4460262 ,  0.40990266, ...,  0.48255903,
          0.62691176,  0.13463421],
        ...,

In [ ]:
bert_results['encoder_outputs'][-1]#it is the same as the sequence output

<tf.Tensor: shape=(2, 128, 768), dtype=float32, numpy=
array([[[ 0.07292046,  0.0856781 ,  0.14476833, ..., -0.0967708 ,
          0.08722136,  0.07711092],
        [ 0.17839377, -0.19006059,  0.5034938 , ..., -0.05869821,
          0.32717127, -0.15578596],
        [ 0.18701449, -0.43388757, -0.48875144, ..., -0.15502799,
          0.0014513 , -0.24470904],
        ...,
        [ 0.12083092,  0.1288425 ,  0.4645352 , ...,  0.07375517,
          0.17441958,  0.16522051],
        [ 0.07967858, -0.01190688,  0.5022545 , ...,  0.13777749,
          0.21002206,  0.00624583],
        [-0.07212721, -0.28303438,  0.5903336 , ...,  0.47551948,
          0.16668488, -0.0892031 ]],

       [[-0.07900605,  0.36335143, -0.2110159 , ..., -0.17183739,
          0.16299734,  0.67242634],
        [ 0.27883568,  0.4371632 , -0.35764813, ..., -0.04463668,
          0.38315186,  0.58879846],
        [ 1.2037671 ,  1.0727025 ,  0.4840873 , ...,  0.24921009,
          0.40730885,  0.40481815],
        ...,